name: CI Build
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  build:
    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    name: CI Build Binary
    runs-on: ubuntu-22.04 # 22 needed for haskell's SDL bindings build
    steps:
      - uses: actions/checkout@v4
      - name: Install OS dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libsdl2-dev libsdl2-image-dev libcairo2-dev libx11-dev libxext-dev libxinerama-dev libxrandr-dev libxss-dev
      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: '9.4.8'
          cabal-version: '3.10.3.0'

      - uses: actions/cache@v4
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-${{ hashFiles('cabal.project.freeze') }}

      - run: cabal build

      - name: copy output binary
        run: cp -v dist-newstyle/build/x86_64-linux/ghc-9.4.8/horus-0.1.0.0/x/horus/build/horus/horus .
      - uses: marvinpinto/action-automatic-releases@latest
        if: github.ref == 'refs/heads/master' # only release on master
        with:
          automatic_release_tag: 'latest'
          prerelease: true
          title: 'Development Build'
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            horus
            LICENSE
