name: CI Build
on: [push]
jobs:
  build:
    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    name: CI Build Binary
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update -y
          sudo apt install -y libsdl2-dev libcairo2-dev libx11-dev libxext-dev libxinerama-dev libxrandr-dev libxss-dev
      - uses: actions/setup-haskell@v1.1
      - run: cabal build
